### ISSUE TITLE
"temporal" the built-in module and the concept Temporal Dead Zone

### ISSUE THREAD

**Issue by rwaldron** [maggiepint/proposal-temporal#10]
I'm not sure I have an opinion either way, but I couldn't help thinking of this when I read the proposal. Obviously there is no _technical_ issue here, but I'm thinking more in terms of those learning language concepts and potential for confusion. Maybe I'm over thinking it?

**Comment by mj1856** [comment]
We were just hunting for a namespace-like term to cluster the various objects together without giving preference to one particular type.  I'm quite interested in other suggestions.

**Comment by maggiepint** [comment]
closing in favor of #12
