### ISSUE TITLE
withMutations() mode

### ISSUE THREAD

**Issue by Turbo87** [maggiepint/proposal-temporal#18]
Immutable.js has a `withMutations()` mode (https://facebook.github.io/immutable-js/docs/#/Map/withMutations) to prevent unnecessary allocations when multiple properties of an object are changed. Since it seems quite common to change e.g. hour, minute and second of a date/time object maybe we should think about something like that too?

**Comment by maggiepint** [comment]
I can see why this might have merit, but given the small size of date objects I'm not sure how necessary it is. Assigning to a later milestone for the moment.

**Comment by mj1856** [comment]
I don't think we want to go here.  Dates are immutable.  We have an open item in #30 for whether or not we want to give functions that change one part at a time (resulting in a new object each time).  If multiple items need to be set simultaneously, one can always just pass them to the constructor together to make a new object..
