### ISSUE TITLE
Differences from date-fns

### ISSUE THREAD

**Issue by lukecwilliams** [maggiepint/proposal-temporal#20]
Interested in what you're proposing here!  Immutability is a big deal for us.

Can you share anything about what you plan to offer above a library like **date-fns**, which operates on Date objects in an immutable fashion?  I suppose one advantage to the new lib is a 100% guarantee that no one will mutate the object.

**Comment by maggiepint** [comment]
This isn't a library.  It is a proposal to change the language-level support for DateTime in ECMA Script, and currently sits at stage 1 in that process. 

I wrote some pretty extensive blog posts about why the native date implementation is broken beyond repair and should be replaced - they can be found here:
https://maggiepint.com/category/date-proposal/

As for why we are doing this at the language level, and not in a library - I addressed that in this issue:
https://github.com/maggiepint/proposal-temporal/issues/19

Does that generally answer your question?

**Comment by lukecwilliams** [comment]
Yes - thank you for the details!  I think what you're saying about library sizes, parsing, and the need for new object because of inability to increment JS's semver makes a lot of sense.  We'd love to have built-in objects with immutability and reliable parsing and we'll watch the project.
