### ISSUE TITLE
Converting from one calendar (e.g., gregorian) to another (e.g., chinese)

### ISSUE THREAD

**Issue by rxaviers** [maggiepint/proposal-temporal#3]
I see an example converting from various timezones:

```js
// Convert between various time zones
var eastUS = new ZonedDateTime('America/New_York', 2017, 1, 1, 0, 0);
var france = eastUS.withZone('Europe/Paris');
var utc = eastUS.withZone('UTC');
var localSystem = eastUS.withZone('SYSTEM');
```

I miss a similar example converting from various calendars.

**Comment by mj1856** [comment]
Yep, we should add that example as well as many others.  Will keep this open to remind us.  Thanks!

**Comment by mj1856** [comment]
We're moving forward with ISO8601 (proleptic Gregorian) only types.  We haven't decided yet whether we'll extend to additional types to support other calendar systems, or if we'll just handline that during parsing/formatting via ECMA-402.
