### ISSUE TITLE
porting conversation from personal repo

### ISSUE THREAD

**Issue by keithamus** [maggiepint/proposal-temporal#37]
I set up a private repo a while ago, with @Nevraeka, in which we attempted to flesh out a spec for datetimes. In the interests of keeping to one solid proposal, I thought it might be useful to shutter that repo and bring the conversation here to get some discussion points for this proposal.

> @keithamus commented on 6 Feb
> I'd like to use this issue to discuss & discover what the high level goals of this spec should be. What we are attempting to do, and what rules & guides we should stick to.
> I'll kick this off with the following points, which I feel is important to a better date lib than what we currently have. In no particular order:
>
> - Constructors should not accept a range of different arguments and formats. Pick one good format (ISO8601), provide supplementary methods for parsing with minimal "magic".
> - Dates should be immutable. Any methods which alter a date should return a new one.
> - Dates should provide some mechanism for safely adding durations of one factor _without_ changing another. For example it should not be possible to do add one month and get back a date two months in the future, or increment the date (0-31) and get back a date that has rolled over to the next month.
> - I would also like to put some thought into how we can provide a decent enough abstraction to support multiple calendars, but this could be impossible to reasonably do.
> - We should provide facilities - where possible - to abstract over common operations which are prone to errors. A fairly concrete example: provide a mechanism for iterating over days in a month.

> @Nevraeka commented on 8 Feb
> 👍 I totally agree with almost all of what you are saying @keithamus - especially on Dates being immutable. Constructors, maybe, could take a few different args & formats (a limited set though that accommodates the major cases).
>
> One item that I have not seen done well in the few languages I looked at are Time Zones. Any thoughts on how Dates 'should' best handle this?
>
> Also - Date objects could be created without using 'new' instances similar (superficially) to `Date.now` or  [Ruby Dates](https://ruby-doc.org/stdlib-2.3.1/libdoc/date/rdoc/Date.html)
>
> For example: `Date.parse` or `Date.strfTime` would implicitly return the new object with the applied transformation. 
>
> this is opposed to ...
>```javascript
>const dateInst = new Date();
>const parsedDate = DATE.parse('12-25-2016');
>```

> @keithamus commented on 8 Feb
> > Constructors, maybe, could take a few different args & formats (a limited set though that accommodates the major cases).
>
> My (probably strong) opinion is that constructors should be single arity. (other than Array (probably wrong here, but off the top of my head)), Date is the only constructor which is A) not single arity, B) variadic, C) has different outputs based on the number of arguments.
> 
> This is not ideal because for every new possible instantiation of a constructor increases the complexity (both code and mental overhead) exponentially. Right now, off the top of my head, I cannot tell you how many different instantiations of Date are possible. 
> 
> However Date has another problem. The other problem is that the "stringly-typed" constructor version, where you parse in a Date string is rife with cross-browser compat issues. Some browsers parse some date string formats, while others don't.
> 
> Even worse than all of that, is that if you actually manage to get a working instantiation, there's still a possibility you'll end up with `Invalid Date`. 
> 
> By specifying a Date constructor which has a fixed and small arity, with a well specified definition of what those arguments should be, and throwing errors when the arguments do not meet these requirements, we can do so much to alleviate the hassle of using Dates. As you suggest, if we want to have some additional mechanisms for parsing arbitrary values into Dates, then we can with static methods, to wit (not formal here, but some ideas):
> 
> ```js
> Date('2017-12-31') // works
> Date(2017, 12, 31) // throws TypeError
> Date.fromNumbers(2017, 12, 31) // works
> Date('12-31-2017', '%m-%d-%Y') // throws TypeError
> Date.strptime('12-31-2017', '%m-%d-%Y') // works
> ```
> 
> > One item that I have not seen done well in the few languages I looked at are Time Zones. Any thoughts on how Dates 'should' best handle this?
> 
> Timezones are especially difficult, both to implement reasonably,  but also to calculate on top of - as they slip and slide and can cause unexpected changes to a Date. Upon some iteration of my original work around this I pretty much settled on the idea that a Date constructor should strip any timezone information upon parse time. It's not ideal because it is a destructive operation, it means Dates become lossy, but in actuality if you want to do any date calculation - you probably want to do it in UTC. In fact ES6 introduced `Date.UTC` to provide this (even if it did include the dreaded words `When the UTC function is called with fewer than two arguments, the behaviour is implementation-dependent`).
> 
> I think, given an opportunity for a new Date constructor, I would make the default ctor strip tz information, and perhaps have an opt-in with a static `Date.tz` which carries timezone information with it. Perhaps passing a tz to the main ctor would throw?
> 
> ```js
> Date('2017-01-01T00:00:00+0400') // throws (Range?)Error
> Date.tz('2017-01-01T00:00:00+0400') // works, you're on your own from here
> ```
> 
> > Also - Date objects could be created without using 'new' instances similar (superficially) to Date.now or Ruby Dates
> 
> I agree with this. Current behaviour is weird - most stdlib ctors work without new, or throw. We should do one or the other, preferably work without `new`.

> @Nevraeka commented on 9 Feb
> Great points on 'single arity'. I can agree. 
> 
> On the note of `Date.UTC` & timezones check out [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat). I still have to look further into this but it seems but since the examples seem to rely on the current Date constructor we would need compat for this as well 

> @Nevraeka commented on 9 Feb
> Also - Once we have a good high level scoping, I would think we should prob consolidate with the other implementers of this to get a holistic approach going to avoid flame warring. Thoughts?

> @keithamus commented on 9 Feb
> Yeah I've had a look at Intl.DateTimeFormat. I think this might be the biggest cause of pain - having both interop with, and extending to that.
>
> > Also - Once we have a good high level scoping, I would think we should prob consolidate with the other implementers of this to get a holistic approach going to avoid flame warring. Thoughts?
>
>Completely agree. Kept this repo private between us until we can flesh out a very loose spec, then we can discuss opening this repo up and getting a wider audience. Want to keep it focussed with us now to avoid getting a bucket of wishes from wider community and ending up with design-by-committee.

**Comment by mj1856** [comment]
Happy to have your input.  Please read through the current revision of the proposal, and the open items.  It think you'll see where this proposal is going, and how it differs from what you've described above.

I think all of the above points are already covered (in spec or in issue), but feel free to create another issue if you see something we missed.

I'm going to close this issue, just because there's not much actionable here.
