### ISSUE TITLE
Do not use pluggable calendars

### ISSUE THREAD

**Issue by jodastephen** [maggiepint/proposal-temporal#5]
The proposed API uses an "options" field to allow for pluggable calendars. As [I wrote](http://blog.joda.org/2009/11/why-jsr-310-isn-joda-time_4941.html) about Joda-Time, making the calendar system a pluggable element of the object is a Bad Idea. Developers will call getMonth() and expect it to return 1 to 12, and then be baffled when it returns 13. Or when the length of a month is 5. The only sane approach is to have the main classes only implement the ISO-8601 civil calendar system (no Julian-Gregorian cutover).

See also [here](https://github.com/ThreeTen/threeten/wiki/Multi-calendar-system) and the architectural issues [here](https://docs.oracle.com/javase/8/docs/api/java/time/chrono/ChronoLocalDate.html). In general, giving developers power over calendar systems is almost always a Bad Idea - they simply won't consider the edge cases properly.

For this API, I would strongly recommend keeping the calendar system completely out of the state of the classes. Instead, pass it in to the formatter, or as a parameter, when needed.

**Comment by mj1856** [comment]
Ok, but it seems like there should still be a way to do things like:

- Input numeric date parts in a specific calendar system
- Add/Subtract months/years in a specific calendar system

Any suggestions?

**Comment by jodastephen** [comment]
Assuming you have a `Chronology` or `CalendarSystem` class, it can have a method `date(y, m, d)` or `date(era, y, m, d)`. The same class can also perform arithmetic - `add(date, amount, amountType)`.

Since there will be an ISO calendar, there is then a consistent accross all calendar systems. Its just that ISO gets some extra functionality from the main date/time classes. (The conceptual leap is understanding that a `LocalDate` may be defined in terms of ISO year/month/day, but it actually represents a "date", which can always be represented/converted to another calendar system.

Note also that Java only localizes dates to a calendar system, not times.

**Comment by ebraminio** [comment]
Just look at what is done already on https://github.com/catull/calendariale it is just what a calendar library on any library should look like

**Comment by mj1856** [comment]
@ebraminio - I'm not sure how that helps us.  Can you give an example that would apply here?

**Comment by ebraminio** [comment]
Usually making calendar pluggable and leaving that problem to third paarty libraries is on believe of that solving the issue is not possible ever and some third party developers should compete with each other and solve that for themselves, which is not true, just some initial i18n consideration can solve that issue which is the case with that library and browser integrated Intl object which is backed by icu4c

**Comment by mj1856** [comment]
We're not proposing leaving it up to developers and making it pluggable in JavaScript.  That wouldn't make sense for this proposal.  We would indeed let implementers back it however they want, and many do indeed use ICU.

The concern being addressed here is if the generic objects such as `LocalDate` should carry a calendar option on them, or if there should be a specific object per calendar such as `IslamicDate`, `GregorianDate`, etc.

The library you pointed at seems to take the latter approach, with objects like `IslamicCalendar` that extend a `BaseCalendar` class.   Personally, I think the terminology is wrong, confusing a calendar with a position on the calendar.  But others have done that before too.

**Comment by ebraminio** [comment]
Thanks, so I just confused a bit here. Of course what was meant was about that kind of plugging and should study more on corner cases advantages/disadvantages of these options. Thanks

**Comment by maggiepint** [comment]
@jonskeet, I would be curious about your opinion here since I know you are into calendars.

**Comment by maggiepint** [comment]
Also, @ichernev and @icambron - think you two might have good perspective or alternatives.

**Comment by ichernev** [comment]
My idea about pluggable calendars (for moment in particular) has always been about adding additional methods/parse format tokens to deal with the other calendar systems, not overwrite the default ones in the horrible scenario described in the first post. The idea being that the core might only support year month date, but with some "calendar plugins" also support the week system (week year, week, day of week), and all other calendars with different method, unit names and tokens.

And the way moment is implemented internally its not that hard to add new units, its just a matter of exposing an api and cleaning a bit.

**Comment by PHPDev-CA** [comment]
ISO 8601 actually calls for timescales of which Julian, Gegorian, etc are a part.  It's actually very important that this standard is followed properly to allow interoperability between different timescales.  

While many people misunderstand ISO8601 due to failing to read the "how to read ISOs" document, the intent of the last major revision was to allow for customizable timescales.  ie:  If I wanted to do a timeline of daily temperatures on Mars I would use a timescale that gives me the d/m/y/etc of Mars' rotations which could operate concurrently with the standard Gregorian methods if say I wanted to show the comparable date on Earth.  It also allows for fictional, segmented (ie: x year to y year), business scales, etc.

To that end nothing should change on the getDate() style methods, however, concurrent timescales should be able to be initiated by the user for comparative, normative, interoperative, and similar purposes.

**Comment by catull** [comment]
@mj1856 Apologies for being late in the discussion, just watched your presentation at JSConf 2017 in Berlin.

I am the developer of [calendariale](https://github.com/catull/calendariale), a port of [Calendrical Calculations](http://www.cambridge.org/ch/academic/subjects/computer-science/computing-general-interest/calendrical-calculations-ultimate-edition-4th-edition?format=HB#fvU35ZcU95BVJpjQ.97) to TypeScript, roughly 31 known calendar systems plus a few more not described in that book.

The original code in Common LISP actually distinguishes dates such as `egyptian-date`, `mayan-tzolkin-date`, `old-hindu-lunar-date` etc.

The naming is not optimal in **calendariale**; the implemented *Calendar classes actually are *Chronology classes, without the `#plusWeek`, `#plusMonth` methods etc.

Perhaps [ecma402](https://github.com/ibm-js/ecma402) or [Intl.js](https://github.com/andyearnshaw/Intl.js) are currently better suited.

*Intl.js* only has the Gregorian calendar system implemented currently.

**Comment by mj1856** [comment]
We're moving forward with ISO8601 (proleptic Gregorian) only types. We haven't decided yet whether we'll extend to additional types to support other calendar systems, or if we'll just handline that during parsing/formatting via ECMA-402.  Either way, we will not have a "pluggable" calendar system.

**Comment by sffc** [comment]
Super old thread, but for the sake of the people subscribed here: we've established calendar support beyond formatting as a key requirement of Temporal, thanks to feedback from TC39-TG2 (the Intl subcommittee, of which I am the chair), and we have made a great deal of progress on how to deal with calendar systems.  See https://github.com/tc39/proposal-temporal/blob/main/docs/calendar.md for the current status.
