### ISSUE TITLE
Define Instant before ZonedDateTime?

### ISSUE THREAD

**Issue by ethanresnick** [maggiepint/proposal-temporal#9]
Apologies if this has been discussed elsewhere; I did a brief search on es-discuss but couldn't find anything.

Anyway, my thought is that `ZonedDateTime`, `Instant` and `OffsetDateTime` all seem to be representations of basically the same thing (a single instant in time), with `ZoneDateTime` and `OffsetDateTime` containing some extra info (the zone or offset) that's not stored in the `Instant` case. To capture this, it seems like it might be good to define `Instant` first, because then the instant could actually be a property on the `ZonedDateTime` and `OffsetDateTime` objects. 

```
Object.keys(new ZonedDateTime()) // ["instant", "zone"]
Object.keys(new OffsetDateTime()) // ["instant", "offset"]
```

Thoughts? I know the realm of dates and timezones is full of subtle distinctions and caveats, so I'm probably overlooking something here...

**Comment by maggiepint** [comment]
I thought about this. Inherently though, Instant doesn't DO something ZonedDateTime can't by being set in UTC. ZonedDateTime, though, can do a lot that Instant can't. Since championing the whole API at once is not really practical, I had to pick and choose. It's certainly quite possible to add instant later.
Thoughts?

**Comment by maggiepint** [comment]
I'm going to close this in favor of #7 as the discussions are in the same vein. This point is quite valid - just want to keep threads together.

**Comment by ethanresnick** [comment]
Sounds good! I'll go take a look at that thread and jump in if I feel there's anything still to add.
